export const projectListData = [
	{
		title: 'LIVHOUSE',
		detailTitle: 'LIVHOUSE',
		category: 'Bilingual apartment rental application',
		status: 'Portfolio / demo application',
		shortDescription:
			'A responsive apartment booking website focused on clear navigation, property presentation, and a simple booking experience.',
		heroDescription:
			'A bilingual full-stack apartment rental application with localized listings, dynamic apartment pages, responsive galleries, and a server-validated booking workflow.',
		poster: '/posters/livhouse.png',
		tags: ['Website', 'Responsive UI', 'Booking'],
		slug: 'livhouse',
		href: '/projects/livhouse',
		overview: [
			'LIVHOUSE is a Russian/English apartment rental portfolio application built with Next.js and TypeScript. It modernizes a legacy rental frontend into a structured application with localized catalog pages, dynamic apartment routes, responsive galleries, and booking workflows.',
			'The booking flow combines client-side validation with server-side request validation and trusted quote calculation, while configurable email delivery supports both local testing and external SMTP environments.',
		],
		features: [
			'Russian and English localization',
			'Locale-aware routes',
			'Apartment catalog',
			'Dynamic apartment detail pages',
			'Responsive image galleries',
			'Home apartment carousel',
			'Reservation workflow',
			'Date, guest, and apartment selection',
			'Client-side booking validation',
			'Server-side booking validation',
			'Trusted server-side quote calculation',
			'CAPTCHA protection',
			'Email delivery through Mailpit or SMTP',
			'Localized SEO metadata',
			'Sitemap and robots endpoints',
			'Accessible responsive navigation',
		],
		stack: [
			'Next.js',
			'React',
			'TypeScript',
			'next-intl',
			'Swiper',
			'Nodemailer',
			'Vitest',
			'ESLint',
			'Docker Compose',
			'Mailpit',
			'GitHub Actions',
		],
		architecture: {
			heading: 'Architecture',
			paragraphs: [
				'Next.js App Router organizes localized server-rendered pages. Typed apartment records act as the shared source for catalog, detail pages, carousel content, and booking options.',
				'Booking requests are processed by a Route Handler that validates the payload again on the server and calculates a trusted quote from the typed apartment data. Request protection includes CAPTCHA checks and bounded request controls.',
			],
		},
		currentStatus: {
			heading: 'Project status',
			paragraphs: [
				'This is a portfolio/demo application with static apartment data. It does not include a production booking database or real payment processing.',
			],
		},
		githubUrl: 'https://github.com/Mariam-sudo514/Apartments-in-Moscow',
		liveUrl: null,
		gallery: [],
	},
	{
		title: 'Drogan VPN',
		detailTitle: 'Drogan VPN',
		category: 'Cross-platform VPN client',
		status: 'In development',
		shortDescription:
			'A cross-platform VPN client built for secure connections, profile management, and a streamlined user experience across desktop and mobile devices.',
		heroDescription:
			'A cross-platform VPN client built with Flutter and sing-box, designed around secure profile management, multi-protocol support, and consistent desktop and mobile experiences.',
		poster: '/posters/VPN.png',
		tags: ['Flutter', 'VPN Client', 'Cross-platform'],
		slug: 'drogan-vpn',
		href: '/projects/drogan-vpn',
		overview: [
			'Drogan VPN is a cross-platform VPN client with shared Flutter UI and business logic across desktop and mobile platforms. The application uses sing-box as the VPN and proxy core and separates shared application logic from platform-specific tunnel integration.',
		],
		features: [
			'WireGuard profile support',
			'VLESS Reality profile support',
			'Shadowsocks profile support',
			'WireGuard `.conf` import',
			'sing-box JSON import',
			'vless:// link import',
			'ss:// link import',
			'Profile validation',
			'Runtime sing-box configuration generation',
			'Secure storage abstraction',
			'Connection state management',
			'Desktop managed sing-box process',
			'Environment checks',
			'Light, dark, and system themes',
		],
		stack: [
			'Flutter',
			'sing-box',
			'flutter_secure_storage',
			'window_manager',
			'MethodChannel',
			'WireGuard',
			'VLESS Reality',
			'Shadowsocks',
		],
		architecture: {
			heading: 'Architecture',
			paragraphs: [
				'Flutter provides the shared UI and application logic. Profile models, import and validation, runtime configuration generation, connection state management, and secure storage are isolated into dedicated service layers.',
				'Desktop builds manage a sing-box process directly without shell execution. Mobile platforms communicate through MethodChannel and require native VPN integration.',
			],
		},
		currentStatus: {
			heading: 'Current status',
			paragraphs: [
				'The shared Flutter application layer, profile models, import and validation, runtime configuration generation, secure storage abstraction, desktop process layer, and environment checks are implemented.',
				'Android and iOS native VPN integration is scaffolded but the mobile sing-box core still needs to be linked. Desktop tunnel startup also requires final verification with a local or bundled sing-box binary and the required operating-system permissions.',
			],
		},
		githubUrl: null,
		liveUrl: null,
		gallery: [],
	},
	{
		title: 'Hutly',
		detailTitle: 'Hutly',
		category: 'Private residential development',
		status: 'Client project',
		shortDescription:
			'A responsive corporate website for a private residential development company, focused on presenting projects, expertise, and premium construction through a structured visual experience.',
		heroDescription:
			'A responsive corporate website for a private residential development company, focused on presenting projects, expertise, and premium construction through a structured visual experience.',
		poster: '/posters/hutly.png',
		tags: ['Corporate Website', 'Frontend', 'Responsive UI'],
		slug: 'hutly',
		href: '/projects/hutly',
		confidentiality: {
			heading: 'Client confidentiality',
			text: "The client identity and selected project details have been anonymized at the client's request.",
		},
		overview: [
			'Hutly is a portfolio presentation of a corporate website created for a private residential development business. The interface focuses on project presentation, company positioning, service communication, and a clean responsive browsing experience.',
		],
		features: [
			'Responsive marketing layout',
			'Project and service presentation',
			'Light and dark theme support',
			'Responsive navigation',
			'Content-focused page sections',
			'Desktop, tablet, and mobile layouts',
		],
		stack: ['React', 'JavaScript', 'Vite'],
		currentStatus: {
			heading: 'Portfolio status',
			paragraphs: [
				'The portfolio version of the project is currently being refined before public repository publication.',
			],
		},
		githubUrl: null,
		liveUrl: null,
		gallery: [],
	},
	{
		title: 'Sales CRM',
		detailTitle: 'Business School CRM',
		category: 'Full-stack CRM',
		status: 'In active development',
		shortDescription:
			'A full-stack sales CRM built to organize leads, track deal progress, manage tasks, and support the daily workflow of sales teams.',
		heroDescription:
			'A full-stack CRM for a business school, built to manage course inquiries, sales pipelines, manager tasks, and customer interactions in one structured workspace.',
		poster: '/posters/CRM.png',
		tags: ['Full-stack', 'CRM', 'Dashboard'],
		slug: 'sales-crm',
		href: '/projects/sales-crm',
		overview: [
			'Business School CRM is a web application designed to organize the daily work of a business school sales team. Incoming course inquiries are registered as leads, assigned to responsible managers, and moved through a structured sales pipeline from initial contact to a completed or lost deal.',
			'The system keeps customer contact details, course interest, tasks, comments, deadlines, interaction history, acquisition sources, and UTM data in one workspace. Role-based access separates the responsibilities of administrators, sales managers, and individual managers.',
		],
		features: [
			'Incoming inquiry registration and processing',
			'Lead assignment between sales managers',
			'Sales pipeline stage management',
			'Course interest linked to leads',
			'Task creation, completion, and cancellation',
			'Customer comments and interaction history',
			'Lead source and UTM tracking',
			'Role-based access control',
			'Audit logging for significant actions',
			'Basic sales analytics',
		],
		stack: [
			'Next.js',
			'React',
			'TypeScript',
			'Tailwind CSS',
			'PostgreSQL',
			'Prisma ORM',
			'Better Auth',
			'Docker Compose',
			'ESLint',
			'Prettier',
			'GitHub Actions',
		],
		architecture: {
			heading: 'Architecture',
			paragraphs: [
				'The application is structured as a modular monolith using Next.js App Router. Server Components handle data retrieval, while mutations execute on the server with mandatory session and permission checks.',
				'The codebase is organized by functional areas, keeping small components isolated and using dedicated component directories only when several related parts need to be grouped together.',
				'The interface is designed for everyday sales operations, with a clear visual hierarchy, responsive layouts, and minimal decorative complexity.',
			],
		},
		githubUrl: null,
		liveUrl: null,
		gallery: [],
	},
	{
		title: 'KinoLook',
		detailTitle: 'KinoLook',
		category: 'Entertainment platform',
		status: 'In active development',
		shortDescription:
			'A movie and series discovery platform with catalog browsing, search, filtering, and a scalable interface for content exploration.',
		heroDescription:
			'A bilingual movie and entertainment discovery platform combining a structured content catalog, full-text search, editorial content, personalization, and scalable backend architecture.',
		poster: '/posters/KinoLook.png',
		tags: ['Next.js', 'TypeScript', 'Movie Platform'],
		slug: 'kinolook',
		href: '/projects/kinolook',
		overview: [
			'KinoLook is an international Russian/English information platform for movies, series, anime, people, franchises, collections, and entertainment industry content.',
			'The platform is designed around discovery: users can search across movies, series, people, and editorial content, navigate related titles, explore similar works, save content, maintain a watchlist, mark titles as watched, rate content, and participate in discussions.',
			'Both Russian and English versions are supported with localized pages, SEO metadata, canonical URLs, hreflang, sitemap generation, and Schema.org structured data.',
		],
		features: [
			'Russian and English localization',
			'Movies and series catalog',
			'Anime and animation content',
			'Actor and crew profiles',
			'Seasons and episodes',
			'Full-text search',
			'Advanced filtering',
			'Related and similar content',
			'Favorites and watchlist',
			'Viewing history',
			'User ratings',
			'Discussions',
			'Franchises and collections',
			'Editorial articles and guides',
			'Official trailer support',
			'Legal availability information',
			'Administrative content management',
			'Metadata import',
			'Moderation',
			'Search indexing',
			'Analytics aggregates',
			'Advertising placement configuration',
		],
		stack: [
			'Next.js',
			'React',
			'TypeScript',
			'NestJS',
			'PostgreSQL',
			'Prisma',
			'Redis',
			'BullMQ',
			'Meilisearch',
		],
		architecture: {
			heading: 'Architecture',
			paragraphs: [
				'KinoLook is structured as a TypeScript monorepo with a Next.js frontend and NestJS backend. PostgreSQL and Prisma provide persistent structured data, Redis and BullMQ support background work, and Meilisearch powers full-text discovery.',
				'The architecture uses typed API contracts, background synchronization, provider-independent metadata imports, provenance tracking, deduplication, secure authentication, RBAC, TOTP, and user session management.',
			],
			diagram: {
				root: 'Next.js',
				api: 'Typed API',
				backend: 'NestJS',
				services: [
					'PostgreSQL / Prisma',
					'Redis',
					'BullMQ',
					'Meilisearch',
				],
			},
		},
		githubUrl: null,
		liveUrl: null,
		gallery: [],
	},
];
